### PR TITLE
Mar databases V3 update

### PR DESCRIPTION
**Pull request by emrobe**
The Mar databases from The Marine Metagenomics Portal (https://mmp.sfb.uit.no/) are now in their third iteration, and I have added some minor codes snippets to account for this.

Version 3 includes over 9000 marine species and the ability to distinguish between reference organisms (MarRef), complete organisms (MarDB) and Metagenomic Assembled Genomes (MarDB MAGS) as defined at the portal.
The makeDB.sh flag -m will download and build the complete database, but for special cases, it is possible to build subsets pertaining to discrete divisions, f.ex only reference sequences (MarRef), by simply commenting out a line or two in the makeDB.sh script. I did not add flags for this, as I do not want to overpopulate the makeDB.sh help text with too much Mar related information. 

Version 2, which is the current integrated DB version in Kaiju atm., will still be supported until this pull request is accepted.

### CODE REVIEW

**Comment by emrobe** [comment]
Will do. I'll create a new pull request in a couple of days.

**Comment by emrobe** [comment]
Yes, that makes sense.
Anyway, i added command line arguments for discrete divisions, and rewrote a bit of the usage() text and build code for Mar databases. The argument parsing bit is not the sexiest of code I've ever written, but it should be POSIX-compliant and work with any combination of flags. But since you are overhauling makeDB.sh anyway, no worries.

**Comment by pmenzel** [comment]
Hm, the server for downloading the data files is not reachable since yesterday

https://s1.sfb.uit.no/public/mar/Resources/kaiju/

any idea?

**Comment by emrobe** [comment]
Yes, we are having a short downtime while doing some updates. It will be online soon.

**Comment by pmenzel** [comment]
Alright!

**Pull request merged**
